### ISSUE TITLE
Release new NPM version

### ISSUE THREAD

**Issue by ali-master** [outerbase/studio#207]
Hi there,

Is there a plan to release a new version of the `@outerbase/studio` NPM package?

**Comment by invisal** [comment]
You mean serving @outerbase/studio via command line? What particular feature you need?

**Comment by ali-master** [comment]
The relations are not displaying, which is a practical feature for us.

**Comment by invisal** [comment]
The ERD does not show all the relation?

**Comment by ali-master** [comment]
> The ERD does not show all the relation?

I need to navigate between relations data not schema

**Comment by invisal** [comment]
Are you referring to this?

![image](https://github.com/user-attachments/assets/32d77e6f-4167-4490-8722-5ef1e73daabb)

**Comment by invisal** [comment]
One more question. Are you primary used from cli or more from desktop app?

**Comment by mon-jai** [comment]
@invisal It would be better if we could install Outerbase Studio with NPM and Docker Compose.

For instance, pgAdmin could be consumed as a docker image, making it easy to integrate into prototype projects as an admin dashboard.

```yml
services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    # Uncomment the following line to enable query logging
    # Then restart the container.
    command: ["postgres", "-c", "log_statement=all"]
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    healthcheck:
      # specifying user and database is needed to avoid `FATAL:  role "root" does not exist`
      # spam in the logs
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 2s
      retries: 20

  pgadmin:
    image: dpage/pgadmin4:8
    restart: unless-stopped
    env_file: .env
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      # https://stackoverflow.com/a/63318968/
      - ./servers.json:/pgadmin4/servers.json
```
